services:
  musicapi:
    container_name: music-api
    image: ${DOCKER_REGISTRY-}musicapi
    build:
      context: .
      dockerfile: MusicApi/Dockerfile
    ports:
      - "8001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_HOST=sqlserver
      - DB_NAME=MusicDB
      - DB_SA_PASSWORD=Admin123!
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_db
    user: "10001:10001"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Admin123!
    ports:
      - "1434:1433"
    volumes:
      - ./sqldata:/var/opt/mssql/data  